### ISSUE TITLE
These pages are out of date, but still linked by google

### ISSUE THREAD

**Issue by mattip** [numba/numba-doc#1]
These pages should be removed from google search results. Apparently google is still indexing them, and the latest release here is two years old. Here are a few techniques to accomplish this or at least indicate to the user that these are old:
- remove them. This may break some internet backlinks, but maybe that is a good thing?
- add `<link rel="[canonical]()" href=` links to https://numba.readthedocs.io/en/stable where the latest documentation lives. 
- add a banner "this is not the latest version ..." like at the top of the [matplotlib](https://matplotlib.org/2.2.5/index.html) documentation

**Comment by seibert** [comment]
Yes, this is on our backlog.  Tracking this issue here: https://github.com/numba/numba/issues/6677
